---
- name: "Tagged block"
  block:
    - name: "Failing if IPv4 address is not defined"
      ansible.builtin.fail:
        msg: "Cannot determine 'ansible_default_ipv4.address'"
      when: ansible_default_ipv4.address is not defined or ansible_default_ipv4.address|length == 0

    - name: "Set k8s defaults"
      ansible.builtin.set_fact:
        custom_registry: "{{ ansible_default_ipv4.address| replace('.','-')+'.sslip.io' }}:5000"
        custom_builder_image: "quay.io/operator_testing/buildah:latest"
        custom_gitInitImage: "quay.io/operator_testing/pipelines-git-init-rhel8:latest"
        custom_env: prod

  tags:
  - tekton-task
  - tekton-pipeline
  - ci
