apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: simple-demo-operator-e2e-test-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
