---
- name: "Upstream community main playbook"
  hosts: all
  become: false
  gather_facts: true
  vars:
    op_work_dir: "{{ ansible_env.HOME }}/.op"
    op_bin_dir: "{{ op_work_dir }}/bin"
    registry_cert_dir: "{{ op_work_dir }}/certs"
    run_cleanup: false
    oc_namespace: default

  environment:
    # User has to do 'export SSL_CERT_DIR=$HOME/.op/certs' when running in rootless mode
    SSL_CERT_DIR: "{{ registry_cert_dir }}"
    PATH: "{{ op_bin_dir }}:{{ ansible_env.PATH }}"

  tasks:
    - name: Debug detection REMOVE
      ansible.builtin.include_role:
        name: install-olm
        tasks_from: detect_olm
      tags:
        - always

    - name: "Upstream community base"
      import_role:
        name: upstream-community-base
      tags:
        - always

    - name: "Install upstream community prerequisites"
      include_role:
        name: install-upstream-community-prerequisites
      when: prerequisites is undefined or prerequisites | bool
      tags:
        - clean
        - install
        - verify

    - debug:
        var: kubeconfig

    - name: "Install kind cluster"
      include_role:
        name: install-kind-cluster
      when: kubeconfig is undefined or kubeconfig | length == 0
      tags:
        - clean
        - install
        - verify
        - kind-install

    - name: "Install OLM"
      include_role:
        name: install-olm
      tags:
        - clean
        - install
        - verify

    - name: "Install Tekton"
      include_role:
        name: install-tekton
      tags:
        - clean
        - install
        - verify

    - name: "Install operator pipeline"
      include_role:
        name: operator-pipeline
      # when: operator-pipeline is defined and operator-pipeline|bool
      tags:
        - tekton-task
        - tekton-pipeline
        - ci

    - name: "Delete kind cluster"
      include_role:
        name: install-kind-cluster
      tags:
        - never
        - kind-delete
