---
- name: "Verify cluster availability"
  block:
    - name: "Verify cluster"
      kubernetes.core.k8s_cluster_info:
      register: api_status_register
      failed_when: false
      when: kubeconfig is not defined or kubeconfig|length == 0

    - name: "Set cluster staus"
      ansible.builtin.set_fact:
        api_status: api_status_register
      when: kubeconfig is not defined or kubeconfig|length == 0

    - name: "Verify cluster with kubeconfig"
      kubernetes.core.k8s_cluster_info:
        kubeconfig: "{{ kubeconfig }}"
      register: api_status
      failed_when: false
      when: 
        - kubeconfig is defined 
        - kubeconfig|length > 0

    - name: "Set cluster staus with kubeconfig"
      ansible.builtin.set_fact:
        api_status: api_status_register
      when: 
        - kubeconfig is defined 
        - kubeconfig|length > 0

    - name: "Failing when cluster is not running"
      ansible.builtin.fail:
        msg: "Cluster is not running !!!"
      when: api_status.failed is undefined or api_status.failed | bool
  tags:
    - always
