---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: upload-artifacts
spec:
  params:
    - name: pyxis_api_key_secret
      default: pyxis-api-secret
    - name: pyxis_url
      default: https://catalog.redhat.com/api/containers/
    - name: log_file
    - name: result_file
    - name: artifacts_dir
    - name: preflight_results_exists
      default: "false"
    - name: md5sum
    - name: cert_project_id
    - name: bundle_version
    - name: package_name
  results:
    - name: log_url
    - name: result_url
  workspaces:
    - name: source
  steps:
    - name: upload-test-logs
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: PYXIS_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.pyxis_api_key_secret)
              key: PYXIS_API_KEY
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          echo "Preflight logs already exists - skipping"
          echo "none" | tee $(results.log_url.path)
          exit 0
        fi

        echo "Uploading test log"

        upload-artifacts \
          --cert-project-id "$(params.cert_project_id)" \
          --operator-version "$(params.bundle_version)" \
          --operator-package-name "$(params.package_name)" \
          --certification-hash "$(params.md5sum)" \
          --pyxis-url "$(params.pyxis_url)" \
          --path "$(params.log_file)" \
          --type preflight-logs \
          --output preflight-logs.json \
          --verbose

        LOG_ID=$(cat preflight-logs.json | jq -r "._id")
        LOG_URL="$(params.pyxis_url)v1/projects/certification/artifacts/id/$LOG_ID"

        echo "Logs URL: "
        echo -n $LOG_URL | tee $(results.log_url.path)

    - name: upload-test-results
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: PYXIS_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.pyxis_api_key_secret)
              key: PYXIS_API_KEY
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          echo "Preflight results already exists - skipping"
          echo "none" | tee $(results.result_url.path)
          exit 0
        fi

        echo "Uploading test results"

        upload-artifacts \
          --cert-project-id "$(params.cert_project_id)" \
          --operator-version "$(params.bundle_version)" \
          --operator-package-name "$(params.package_name)" \
          --certification-hash "$(params.md5sum)" \
          --pyxis-url "$(params.pyxis_url)" \
          --path "$(params.result_file)" \
          --type preflight-results \
          --output preflight-results.json \
          --verbose

        RESULTS_ID=$(cat preflight-results.json| jq -r "._id")
        RESULT_URL="$(params.pyxis_url)v1/projects/certification/id/$(params.cert_project_id)/test-results/$RESULTS_ID"

        echo "Test result URL: "
        echo -n $RESULT_URL | tee $(results.result_url.path)

    - name: upload-test-artifacts
      image: quay.io/redhat-isv/operator-pipelines-images:latest
      workingDir: $(workspaces.source.path)
      env:
        - name: PYXIS_API_KEY
          valueFrom:
            secretKeyRef:
              name: $(params.pyxis_api_key_secret)
              key: PYXIS_API_KEY
      script: |
        #! /usr/bin/env bash
        PREFLIGHT_RESULTS_EXISTS="$(params.preflight_results_exists)"
        if [ $PREFLIGHT_RESULTS_EXISTS == "true" ]; then
          exit 0
        fi

        echo "Uploading test artifacts"

        upload-artifacts \
          --cert-project-id "$(params.cert_project_id)" \
          --operator-version "$(params.bundle_version)" \
          --operator-package-name "$(params.package_name)" \
          --certification-hash "$(params.md5sum)" \
          --pyxis-url "$(params.pyxis_url)" \
          --path "$(params.artifacts_dir)" \
          --type preflight-artifacts \
          --output preflight-artifacts.json \
          --verbose
