---
- name: "OLM detection"
  block:

    # - name: "Get all namespaces"
    #   kubernetes.core.k8s_info:
    #     kind: Namespace
    #   register: io_olm_namespaces

    # - debug:
    #     var: io_olm_namespaces

    - name: "Get all pods"
      kubernetes.core.k8s_info:
        kind: Pod
        # name: "olm-operator"
        # namespace: olm
      register: io_olm_pods

    - debug:
        var: io_olm_pods

    - name: "Extract 'resources'"
      ansible.builtin.set_fact:
        pod_list_extended: "{{ io_olm_pods.resources|list }}"

    - name: "Loop over running operators"
      ansible.builtin.include_tasks:
        file: "detect_olm_version.yml"
      loop: "{{ pod_list_extended }}"
      #   loop_var: operator_data

    - debug:
        var: iom_olm_operator_name

    - debug:
        var: iom_olm_operator_namespace

    - name: "Get OLM version from iom_olm_operator_name"
      kubernetes.core.k8s_exec:
        namespace: "{{ iom_olm_operator_namespace }}"
        pod: "{{ iom_olm_operator_name }}"
        command: olm --version
      register: olm_version_detected_output

    - debug:
        var: (olm_version_detected_output.stdout_lines|first).split('v')[2]

    - pause:

    - name: "OLM is not needed"
      ansible.builtin.set_fact:
        olm_needed: false
      when: "'olm-operator' in io_pod_list"
  tags:
    - install
