---
- name: "OLM detection"
  block:
    - debug:
        var: cluster_binary

    - name: "Checking OLM presence"
      ansible.builtin.command: "{{ cluster_binary }} get pods --all-namespaces |grep olm-operator"
      failed_when: false
      register: io_olm_presence

    - name: "OLM is not needed"
      ansible.builtin.set_fact:
        olm_needed: false
      when: io_olm_presence.rc == 0
  tags:
    - install
