---
- name: "OLM detection"
  block:

    - name: "Get all pods"
      kubernetes.core.k8s_info:
        kind: Pod
      register: io_olm_pods

    - name: "Extract 'resources'"
      ansible.builtin.set_fact:
        pod_list_extended: "{{ io_olm_pods.resources|list }}"

    - name: "Loop over running operators"
      ansible.builtin.include_tasks:
        file: "detect_olm_version.yml"
      loop: "{{ pod_list_extended }}"

    - name: ""
      ansible.builtin.set_fact:
        olm_is_running: false
      when: 
        - iom_olm_operator_name is defined
        - iom_olm_operator_name| length >0

    - name: "Get OLM version from iom_olm_operator_name"
      kubernetes.core.k8s_exec:
        namespace: "{{ iom_olm_operator_namespace }}"
        pod: "{{ iom_olm_operator_name }}"
        command: olm --version
      register: olm_version_detected_output
      when:
        - olm_is_running is defined
        - olm_is_running|bool


    - name: "Set OLM detected version"
      ansible.builtin.set_fact:
        olm_version_detected: "v{{ (olm_version_detected_output.stdout_lines|first).split('v')[2] }}"
      when:
        - olm_is_running is defined
        - olm_is_running|bool

    - name: "OLM is not needed, when existing {{ olm_version_detected }} is defined and correct"
      ansible.builtin.set_fact:
        olm_needed: false
      when: 
        - olm_version_detected is defined
        - olm_version_detected == olm_version
  tags:
    - install
