---
- name: "Uninstall OLM"
  ansible.builtin.command: "{{ op_bin_dir }}/{{ operator_sdk_binary }} olm uninstall --version {{ olm_version }} --timeout 5m0s"
  changed_when: true
  failed_when: false
  register: olm_uninstall_rc
  tags:
    - clean

- name: "Detect if OLM is present"
  block:
    - name: "Set OLM needed default"
      ansible.builtin.set_fact:
        olm_needed: true

    - name: "OLM detection"
      ansible.builtin.include_tasks:
        file: detect_olm.yml
  tags:
    - install

- name: "Install OLM"
  block:
    - name: "Installing OLM ({{ olm_version }})"
      ansible.builtin.command: "{{ op_bin_dir }}/{{ operator_sdk_binary }} olm install --version {{ olm_version }} --timeout 5m0s"
      changed_when: true
      register: olm_install_rc
  when: olm_needed|bool
  tags:
    - install
